version: '2'

services:
    php:
        build: docker/php7-fpm
        volumes:
            - ./:/var/www/symfony
            - ./docker/logs/symfony:/var/www/symfony/app/logs

    nginx:
        build: docker/nginx
        ports:
            - 80:80
        volumes_from:
            - php
        volumes:
            - ./docker/logs/nginx/:/var/log/nginx
